joint_publisher:
  type: joint_state_controller/JointStateController
  publish_rate: 50  

velocity_controller:
  type: "diff_drive_controller/DiffDriveController"
  left_wheel: 'left_wheel_hinge'
  right_wheel: 'right_wheel_hinge'
  pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  always_on : true  
  wheel_separation : 0.14
  wheel_radius : 0.05
  # Wheel separation and radius multipliers
  wheel_separation_multiplier: 1.0 # default: 1.0
  wheel_radius_multiplier    : 1.0 # default: 1.0

  # Velocity commands timeout [s], default 0.5
  cmd_vel_timeout: 0.5

    # Odometry fused with IMU is published by robot_localization, so
  # no need to publish a TF based on encoders alone.
  enable_odom_tf: false
  base_frame_id: chassis
  # Velocity and acceleration limits
  # Whenever a min_* is unspecified, default to -max_*
  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 3.0  # (108 [Max Wheel RPM] * 2 * PI * 0.08[Radius]) / 60 [m/s] 
      min_velocity           : -3.0  # m/s
      has_acceleration_limits: true
      max_acceleration       : 0.5   # m/s^2
      min_acceleration       : -0.5  # m/s^2
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 3.14   # rad/s
      min_velocity           : -3.14  # rad/s
      has_acceleration_limits: true
      max_acceleration       : 0.5   # rad/s^2
      min_acceleration       : -0.5   # rad/s^2